### ISSUE TITLE
Readme paths redirecting to the wrong page

### ISSUE THREAD

**Issue by fernandorpm** [microverseinc/readme-template#6]
# Readme paths redirecting to the wrong page
> Both the Linkedin profile URL and the issues page URL takes the user to non-existent pages (404)

## Why change it on the template instead of relying on the developer
The template should be as straightforward as possible, and avoid as many confusions as possible.
Microverse can be quite challenging when you first get into it with all of its requirements, documentation, and so on, so we should always try to remove as many burdens as we can from our students' backs.

## Linkedin Profile Page URL
How it is right now:
`- LinkedIn: [LinkedIn](https://linkedin.com/linkedinhandle)`

How it should be:
`- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)`
> This way all that is required to change is the handle

## Issues Page on Github URL
How it is right now:
`Feel free to check the [issues page](issues/).`

How it should be:
`Feel free to check the [issues page](../../issues/).`
> This way nothing has to be done on the developer's side

## Additional suggestions :rocket:
Add an MIT Template file as well. It could even be pointed out that students should always try to improve the file and have their own default MIT file. But for starters, it is a timesaver, especially if we consider that not all code reviewers actually ask them to update/fix the link, and for their first requested changes, they most likely won't even know where to look at it or what're they talking about.

**Comment by Spayco** [comment]
@fernandorpm would you wanna create a PR fixing this issue? or should I do it

**Comment by fernandorpm** [comment]
Done bro! :+1:
